//! Plan Plane issues for a design swap. Two shapes:
//!
//! - `Plan::PerArea` — one IMPROVEMENT issue per impacted area (the M7
//!   default; correct for *partial* swaps).
//! - `Plan::FullRewrite { epic, children }` — one EPIC + N child issues
//!   (M-D2; correct for *catalog* swaps where most areas change at once).
//!   Each child carries the EPIC's title in its description so Plane
//!   flavors that don't natively model parents still keep the connection
//!   visible on the board.
//!
//! `auto_plan` chooses between the two given a threshold (default 4 of 7
//! areas) — `cmd_design swap` overrides that with `--per-area` /
//! `--full-rewrite` flags.

use serde::{Deserialize, Serialize};

use crate::diff::ImpactArea;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedIssue {
    pub title: String,
    pub description: String,
    pub label: String,
    pub area: ImpactArea,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedEpic {
    /// Title of the parent EPIC, e.g. "[design] Adopt posthog design system".
    pub title: String,
    /// Descriptive body — preview URL + child summary block.
    pub description: String,
    /// EPIC label (default "EPIC"; Plane flavors that don't have an EPIC
    /// label can map this to "improvement" + custom property).
    pub label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Plan {
    /// One IMPROVEMENT per area.
    PerArea(Vec<PlannedIssue>),
    /// One EPIC + per-area children. Children's `description` references
    /// the EPIC by title so Plane upstream (no native parent_id) still
    /// shows a coherent group on the board.
    FullRewrite {
        epic: PlannedEpic,
        children: Vec<PlannedIssue>,
    },
}

impl Plan {
    /// Total number of issues that will be created (EPIC counts as one).
    pub fn issue_count(&self) -> usize {
        match self {
            Plan::PerArea(items) => items.len(),
            Plan::FullRewrite { children, .. } => 1 + children.len(),
        }
    }

    /// Flat iterator over `(label, title)` for compact CLI output.
    pub fn flat_titles(&self) -> Vec<(String, String)> {
        match self {
            Plan::PerArea(items) => items
                .iter()
                .map(|i| (i.label.clone(), i.title.clone()))
                .collect(),
            Plan::FullRewrite { epic, children } => {
                let mut v = vec![(epic.label.clone(), epic.title.clone())];
                v.extend(children.iter().map(|c| (c.label.clone(), c.title.clone())));
                v
            }
        }
    }
}

/// Choice surfaced to the CLI. `Auto` consults a threshold; the others are
/// explicit operator overrides.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlanMode {
    /// Default. Threshold-based: `>= threshold` → FullRewrite, else PerArea.
    Auto,
    PerArea,
    FullRewrite,
}

/// Default auto-threshold: the legacy `ImpactArea` enum has 7 variants, so
/// "≥ 4 of 7" is "majority of areas changed".
pub const DEFAULT_FULL_REWRITE_THRESHOLD: usize = 4;

pub fn plan(areas: &[ImpactArea], reference_url: &str) -> Vec<PlannedIssue> {
    plan_per_area(areas, reference_url)
}

fn plan_per_area(areas: &[ImpactArea], reference_url: &str) -> Vec<PlannedIssue> {
    areas
        .iter()
        .copied()
        .map(|area| PlannedIssue {
            title: format!("[design] update {} from {}", area.slug(), reference_url),
            description: format!(
                "Auto-generated by `genasis design swap`.\n\nReference: {reference_url}\nArea: {}\n\nReview docs/design-system.md (or docs/design-system/DESIGN.md if external) and update affected components to match the new tokens.",
                area.slug()
            ),
            label: "IMPROVEMENT".into(),
            area,
        })
        .collect()
}

fn plan_full_rewrite(
    areas: &[ImpactArea],
    reference_url: &str,
    slug: &str,
    preview_url: &str,
) -> (PlannedEpic, Vec<PlannedIssue>) {
    let epic_title = format!("[design] Adopt {slug} design system");
    let mut child_summary = String::new();
    for area in areas {
        child_summary.push_str(&format!("- [{}] {}\n", "IMPROVEMENT", area.slug()));
    }
    let epic = PlannedEpic {
        title: epic_title.clone(),
        description: format!(
            "Auto-generated by `genasis design swap`.\n\nFull-rewrite mode — the active design system has been replaced.\n\nReference: {reference_url}\nSlug: {slug}\nPreview: {preview_url}\n\nChild issues (one per impacted area):\n{child_summary}\nThis EPIC closes when every child issue is closed. UI agents should\nconsult `docs/design-system.md` (and the external `docs/design-system/DESIGN.md`)\nbefore touching any component."
        ),
        label: "EPIC".into(),
    };
    let children: Vec<PlannedIssue> = areas
        .iter()
        .copied()
        .map(|area| PlannedIssue {
            title: format!("[design][{}] update {} for {slug}", area.slug(), area.slug()),
            description: format!(
                "Parent EPIC: \"{epic_title}\"\n\nReference: {reference_url}\nArea: {}\n\nUpdate affected components to match the new tokens defined in the\nactive `docs/design-system/DESIGN.md`. Coordinate with the EPIC so the\nrewrite lands as one cohesive change.",
                area.slug()
            ),
            label: "IMPROVEMENT".into(),
            area,
        })
        .collect();
    (epic, children)
}

/// Pick a plan shape based on the requested mode and the number of changed
/// areas. `slug` and `preview_url` are only consumed by the full-rewrite
/// shape; pass empty strings if you do not have them (per-area is unaffected).
pub fn auto_plan(
    mode: PlanMode,
    areas: &[ImpactArea],
    reference_url: &str,
    slug: &str,
    preview_url: &str,
    threshold: usize,
) -> Plan {
    let force_full = matches!(mode, PlanMode::FullRewrite);
    let force_per_area = matches!(mode, PlanMode::PerArea);
    let auto_full = matches!(mode, PlanMode::Auto) && areas.len() >= threshold;
    if force_full || auto_full {
        if !force_per_area {
            let (epic, children) = plan_full_rewrite(areas, reference_url, slug, preview_url);
            return Plan::FullRewrite { epic, children };
        }
    }
    Plan::PerArea(plan_per_area(areas, reference_url))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn five_areas() -> Vec<ImpactArea> {
        vec![
            ImpactArea::ColorTokens,
            ImpactArea::Typography,
            ImpactArea::Spacing,
            ImpactArea::Components,
            ImpactArea::Motion,
        ]
    }

    #[test]
    fn one_issue_per_area() {
        let areas = vec![ImpactArea::ColorTokens, ImpactArea::Spacing];
        let issues = plan(&areas, "https://gumroad.com");
        assert_eq!(issues.len(), 2);
        assert!(issues[0].title.contains("color-tokens"));
        assert!(issues[1].title.contains("spacing"));
        assert!(issues.iter().all(|i| i.label == "IMPROVEMENT"));
    }

    #[test]
    fn auto_below_threshold_returns_per_area() {
        let p = auto_plan(
            PlanMode::Auto,
            &[ImpactArea::ColorTokens, ImpactArea::Typography],
            "u",
            "posthog",
            "p",
            DEFAULT_FULL_REWRITE_THRESHOLD,
        );
        match p {
            Plan::PerArea(items) => assert_eq!(items.len(), 2),
            Plan::FullRewrite { .. } => panic!("expected per-area"),
        }
    }

    #[test]
    fn auto_at_threshold_returns_full_rewrite() {
        let areas = five_areas();
        let p = auto_plan(
            PlanMode::Auto,
            &areas,
            "u",
            "posthog",
            "https://getdesign.md/posthog/design-md",
            DEFAULT_FULL_REWRITE_THRESHOLD,
        );
        match p {
            Plan::FullRewrite { epic, children } => {
                assert_eq!(epic.label, "EPIC");
                assert!(epic.title.contains("posthog"));
                assert!(epic.description.contains("https://getdesign.md/posthog"));
                assert_eq!(children.len(), areas.len());
                // Children must reference the EPIC title.
                let parent = epic.title.clone();
                assert!(children.iter().all(|c| c.description.contains(&parent)));
            }
            Plan::PerArea(_) => panic!("expected full-rewrite at threshold"),
        }
    }

    #[test]
    fn force_per_area_overrides_threshold() {
        let p = auto_plan(
            PlanMode::PerArea,
            &five_areas(),
            "u",
            "posthog",
            "p",
            DEFAULT_FULL_REWRITE_THRESHOLD,
        );
        assert!(matches!(p, Plan::PerArea(_)));
    }

    #[test]
    fn force_full_rewrite_overrides_low_count() {
        let p = auto_plan(
            PlanMode::FullRewrite,
            &[ImpactArea::ColorTokens],
            "u",
            "posthog",
            "p",
            DEFAULT_FULL_REWRITE_THRESHOLD,
        );
        assert!(matches!(p, Plan::FullRewrite { .. }));
    }

    #[test]
    fn issue_count_includes_epic() {
        let p = auto_plan(
            PlanMode::FullRewrite,
            &five_areas(),
            "u",
            "posthog",
            "p",
            DEFAULT_FULL_REWRITE_THRESHOLD,
        );
        assert_eq!(p.issue_count(), 1 + 5);
    }
}
