//! Emit one Plane IMPROVEMENT-labelled issue per impacted area when the
//! design system changes.
//!
//! The emitter is deliberately decoupled from the Plane provider crate —
//! it returns a plan of issues to create, and the caller (cmd_design)
//! invokes the provider. This keeps the design crate independent of any
//! specific Plane flavor.

use serde::{Deserialize, Serialize};

use crate::diff::ImpactArea;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedIssue {
    pub title: String,
    pub description: String,
    pub label: String,
    pub area: ImpactArea,
}

pub fn plan(areas: &[ImpactArea], reference_url: &str) -> Vec<PlannedIssue> {
    areas
        .iter()
        .copied()
        .map(|area| PlannedIssue {
            title: format!("[design] update {} from {}", area.slug(), reference_url),
            description: format!(
                "Auto-generated by `genasis design swap`.\n\nReference: {reference_url}\nArea: {}\n\nReview docs/design-system.md and update affected components to match the new tokens.",
                area.slug()
            ),
            label: "IMPROVEMENT".into(),
            area,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_issue_per_area() {
        let areas = vec![ImpactArea::ColorTokens, ImpactArea::Spacing];
        let issues = plan(&areas, "https://gumroad.com");
        assert_eq!(issues.len(), 2);
        assert!(issues[0].title.contains("color-tokens"));
        assert!(issues[1].title.contains("spacing"));
        assert!(issues.iter().all(|i| i.label == "IMPROVEMENT"));
    }
}
