#!/usr/bin/env bash
# setup-user-env.sh — generate per-operator .env files for a multi-tenant
# Genasis stack (Plane + Mattermost) on a shared host.
#
# Writes:
#   servers/.env       (Plane + Mattermost stack)
#
# (As of v0.6+, trial-app is operated separately at
# https://genasis-trial.realstory.blog — sources in agents-pool/trial-app/,
# deployment in /work/genasis-trial/. This script no longer touches it.)
#
# Allocation strategy
# -------------------
#   COMPOSE_PROJECT_NAME = genasis-${USER}
#   offset               = $(id -u) % 50
#   PLANE_PORT           = 38400 + offset
#   MM_PORT              = 38500 + offset
#
# If any of those host ports is already bound by another process, we
# walk forward until we find a free one (still keeping both on the
# same offset to keep mental model simple).
#
# Secrets are generated with `openssl rand -hex 30`; rerun the script
# only if you intend to rotate them — rerunning preserves passwords if
# servers/.env already has non-CHANGE_ME values, by default.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
servers_env="${repo_root}/servers/.env"

force=false
for arg in "$@"; do
  case "$arg" in
    -f|--force) force=true ;;
    -h|--help)
      sed -n '2,20p' "$0"
      exit 0
      ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [[ -f "$servers_env" && "$force" != true ]]; then
  echo "✗ ${servers_env} already exists. Re-run with --force to regenerate." >&2
  echo "   (this would rotate passwords; back up the existing file first)" >&2
  exit 1
fi

# ─── allocate ports ─────────────────────────────────────────
uid="$(id -u)"
user_name="${USER:-$(id -un)}"
offset=$(( uid % 50 ))

port_in_use() {
  # cross-platform-ish: try ss first (Linux), fall back to lsof (macOS)
  if command -v ss >/dev/null 2>&1; then
    ss -tlnH 2>/dev/null | awk '{print $4}' | grep -qE "[:.]$1\$"
  elif command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
  else
    return 1  # cannot detect — proceed optimistically
  fi
}

next_free_offset() {
  local base_p="$1" base_m="$2" off="$3" max=50
  while [[ $off -lt $max ]]; do
    if ! port_in_use $((base_p + off)) \
       && ! port_in_use $((base_m + off)); then
      echo "$off"
      return 0
    fi
    off=$((off + 1))
  done
  echo "✗ no free port slot in offset range [0,$max). Tried bases $base_p/$base_m." >&2
  exit 1
}

free_offset=$(next_free_offset 38400 38500 "$offset")
plane_port=$((38400 + free_offset))
mm_port=$((38500 + free_offset))

# ─── secrets ───────────────────────────────────────────────
gen_secret() { openssl rand -hex 30; }
plane_pw=$(gen_secret)
mm_pw=$(gen_secret)
plane_secret=$(gen_secret)
webhook_secret=$(gen_secret)

# ─── write servers/.env ────────────────────────────────────
cat >"$servers_env" <<EOF
# Generated by setup-user-env.sh on $(date -Iseconds) for user "${user_name}" (uid=${uid}).
# Re-run with --force to rotate.

COMPOSE_PROJECT_NAME=genasis-${user_name}

PLANE_DOMAIN=${user_name}-plane.example.com
MM_DOMAIN=${user_name}-mm.example.com

PLANE_PORT=${plane_port}
MM_PORT=${mm_port}

APP_RELEASE=v1.2.3
PLANE_POSTGRES_USER=plane
PLANE_POSTGRES_PASSWORD=${plane_pw}
PLANE_SECRET_KEY=${plane_secret}

MATTERMOST_IMAGE_TAG=10.11.8
MM_POSTGRES_USER=mmuser
MM_POSTGRES_PASSWORD=${mm_pw}

WEBHOOK_SHARED_SECRET=${webhook_secret}

TZ=Asia/Seoul
EOF
chmod 600 "$servers_env"

# ─── summary ───────────────────────────────────────────────
cat <<EOF

✓ wrote ${servers_env}

Allocated for user "${user_name}" (uid=${uid}, offset=${free_offset}):
  PLANE_PORT       ${plane_port}
  MM_PORT          ${mm_port}

Suggested domains (edit ${servers_env} if your DNS differs):
  https://${user_name}-plane.example.com   →   localhost:${plane_port}
  https://${user_name}-mm.example.com      →   localhost:${mm_port}

Next steps:
  1) Add a Caddy import for your sub-domains (see servers/README §Multi-tenant).
  2) cd servers && docker compose up -d

Trial app (optional, separate): runs on this host's
  https://genasis-trial.realstory.blog
  via /work/genasis-trial/ — see that directory's README.
EOF
