//! ADR-019 §4 + secrets policy: write `genasis.toml` + `.env.local` +
//! `provision.log` for a freshly-provisioned team.
//!
//! Two output strategies, picked at runtime:
//!
//! - **Operator (`GENASIS_SECRETS_ROOT` env set)** — writes into
//!   `<root>/teams/<team-slug>/`. Designed for agents-pool's
//!   `secrets/` tree (see `agents-pool/secrets/README.md`). All three
//!   files are versioned in the private repo for audit / recovery.
//!
//! - **End-user (env unset)** — writes into the `--output` directory
//!   (cwd by default). Caller is expected to `chmod 600` the
//!   `.env.local` and add it to their own `.gitignore`.
//!
//! Everything written here is **idempotent**: `.env.local` is
//! deserialized in place if it already exists so subsequent runs
//! merge new tokens instead of clobbering existing ones; the toml
//! snapshot is rebuilt from scratch each run (it's the authoritative
//! view of what's provisioned right now); `provision.log` is
//! append-only with a timestamped header per run.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use chrono::Local;

/// The collected output of one `genasis provision` (or follow-up
/// `genasis team`) run. The writer transforms this into three files
/// on disk.
#[derive(Debug, Clone)]
pub struct ProvisionRecord {
    pub team_name: String,
    pub team_slug: String,
    pub app_name: String,
    pub app_slug: String,
    pub plane: PlaneRecord,
    pub mattermost: MattermostRecord,
    pub humans: Vec<HumanRecord>,
    pub agents: Vec<AgentRecord>,
}

#[derive(Debug, Clone)]
pub struct PlaneRecord {
    pub url: String,
    pub workspace_slug: String,
    pub project_id: String,
    pub project_identifier: String,
    pub project_name: String,
}

#[derive(Debug, Clone)]
pub struct MattermostRecord {
    pub url: String,
    pub team_id: String,
    pub team_name: String,
    pub scrum_channel_id: String,
    pub scrum_channel_name: String,
}

#[derive(Debug, Clone)]
pub struct HumanRecord {
    pub name: String,
    pub email: String,
    pub username: String,
    pub plane_user_id: Option<String>, // None when invitation still pending
    pub mm_user_id: Option<String>,
}

#[derive(Debug, Clone)]
pub struct AgentRecord {
    pub role: String,
    pub email: String,
    pub plane_user_id: Option<String>,
    pub plane_pat: Option<String>, // None when reusing a globally-shared agent
    pub mm_user_id: String,
    pub mm_pat: String,
}

/// Resolve where to write — `GENASIS_SECRETS_ROOT/teams/<slug>` when
/// the env var is set, otherwise `output_dir` directly.
pub fn output_dir_for(record: &ProvisionRecord, fallback_output: &Path) -> Result<PathBuf> {
    if let Ok(root) = std::env::var("GENASIS_SECRETS_ROOT") {
        let dir = Path::new(&root).join("teams").join(&record.team_slug);
        fs::create_dir_all(&dir)
            .with_context(|| format!("create secrets dir {}", dir.display()))?;
        Ok(dir)
    } else {
        fs::create_dir_all(fallback_output)
            .with_context(|| format!("create output dir {}", fallback_output.display()))?;
        Ok(fallback_output.to_path_buf())
    }
}

/// Write all three artifacts. Returns the final directory so the
/// caller can print it in the summary.
pub fn write_all(record: &ProvisionRecord, fallback_output: &Path) -> Result<PathBuf> {
    let dir = output_dir_for(record, fallback_output)?;
    write_genasis_toml(&dir, record)?;
    write_env_local(&dir, record)?;
    append_provision_log(&dir, record)?;
    Ok(dir)
}

fn write_genasis_toml(dir: &Path, record: &ProvisionRecord) -> Result<()> {
    let path = dir.join("genasis.toml.snapshot");
    let mut body = String::new();
    body.push_str("# Generated by `genasis provision` / `genasis team`.\n");
    body.push_str("# Versioned snapshot of what's currently provisioned.\n");
    body.push_str(&format!(
        "# Last update: {}\n\n",
        Local::now().to_rfc3339()
    ));

    body.push_str("[provision]\n");
    body.push_str(&format!(
        "provisioned_at = \"{}\"\n",
        Local::now().to_rfc3339()
    ));
    body.push_str(&format!("team_name = {}\n", toml_quote(&record.team_name)));
    body.push_str(&format!("team_slug = {}\n", toml_quote(&record.team_slug)));
    body.push_str(&format!("app_name  = {}\n", toml_quote(&record.app_name)));
    body.push_str(&format!("app_slug  = {}\n", toml_quote(&record.app_slug)));
    body.push('\n');

    body.push_str("[plane]\n");
    body.push_str("flavor = \"real\"\n");
    body.push_str(&format!("url = {}\n", toml_quote(&record.plane.url)));
    body.push_str(&format!(
        "workspace_slug = {}\n",
        toml_quote(&record.plane.workspace_slug)
    ));
    body.push_str(&format!(
        "project_id = {}\n",
        toml_quote(&record.plane.project_id)
    ));
    body.push_str(&format!(
        "project_identifier = {}\n",
        toml_quote(&record.plane.project_identifier)
    ));
    body.push_str(&format!(
        "project_name = {}\n",
        toml_quote(&record.plane.project_name)
    ));
    body.push('\n');

    body.push_str("[mattermost]\n");
    body.push_str("flavor = \"real\"\n");
    body.push_str(&format!("url = {}\n", toml_quote(&record.mattermost.url)));
    body.push_str(&format!(
        "team_id = {}\n",
        toml_quote(&record.mattermost.team_id)
    ));
    body.push_str(&format!(
        "team_name = {}\n",
        toml_quote(&record.mattermost.team_name)
    ));
    body.push_str(&format!(
        "scrum_channel_id = {}\n",
        toml_quote(&record.mattermost.scrum_channel_id)
    ));
    body.push_str(&format!(
        "scrum_channel_name = {}\n",
        toml_quote(&record.mattermost.scrum_channel_name)
    ));
    body.push('\n');

    for h in &record.humans {
        body.push_str("[[humans]]\n");
        body.push_str(&format!("name = {}\n", toml_quote(&h.name)));
        body.push_str(&format!("email = {}\n", toml_quote(&h.email)));
        body.push_str(&format!("username = {}\n", toml_quote(&h.username)));
        if let Some(id) = &h.plane_user_id {
            body.push_str(&format!("plane_user_id = {}\n", toml_quote(id)));
        }
        if let Some(id) = &h.mm_user_id {
            body.push_str(&format!("mm_user_id = {}\n", toml_quote(id)));
        }
        body.push('\n');
    }

    for a in &record.agents {
        body.push_str("[[agents]]\n");
        body.push_str(&format!("role = {}\n", toml_quote(&a.role)));
        body.push_str(&format!("email = {}\n", toml_quote(&a.email)));
        if let Some(id) = &a.plane_user_id {
            body.push_str(&format!("plane_user_id = {}\n", toml_quote(id)));
        }
        body.push_str(&format!("mm_user_id = {}\n", toml_quote(&a.mm_user_id)));
        body.push('\n');
    }

    atomic_write(&path, &body)?;
    Ok(())
}

fn write_env_local(dir: &Path, record: &ProvisionRecord) -> Result<()> {
    let path = dir.join(".env.local");
    let existing = read_env_kv(&path).unwrap_or_default();
    let mut merged: BTreeMap<String, String> = existing;

    // Top-level identifiers. Always overwrite — these are the
    // authoritative source-of-truth from the current provision run.
    merged.insert("GENASIS_TEAM_NAME".into(), record.team_name.clone());
    merged.insert("GENASIS_TEAM_SLUG".into(), record.team_slug.clone());
    merged.insert("GENASIS_APP_NAME".into(), record.app_name.clone());
    merged.insert("GENASIS_APP_SLUG".into(), record.app_slug.clone());

    merged.insert("PLANE_URL".into(), record.plane.url.clone());
    merged.insert(
        "PLANE_WORKSPACE_SLUG".into(),
        record.plane.workspace_slug.clone(),
    );
    merged.insert("PLANE_PROJECT_ID".into(), record.plane.project_id.clone());
    merged.insert(
        "PLANE_PROJECT_IDENTIFIER".into(),
        record.plane.project_identifier.clone(),
    );

    merged.insert("MM_URL".into(), record.mattermost.url.clone());
    merged.insert("MM_TEAM_ID".into(), record.mattermost.team_id.clone());
    merged.insert(
        "MM_TEAM_NAME".into(),
        record.mattermost.team_name.clone(),
    );
    merged.insert(
        "MM_SCRUM_CHANNEL_ID".into(),
        record.mattermost.scrum_channel_id.clone(),
    );
    merged.insert(
        "MM_SCRUM_CHANNEL_NAME".into(),
        record.mattermost.scrum_channel_name.clone(),
    );

    // Per-agent rows. Role names may contain hyphens (e.g.
    // `code-reviewer`) which aren't legal in shell vars — convert to
    // underscores + uppercase.
    for a in &record.agents {
        let key = role_env_key(&a.role);
        if let Some(id) = &a.plane_user_id {
            merged.insert(format!("PLANE_AGENT_USERID_{key}"), id.clone());
        }
        if let Some(pat) = &a.plane_pat {
            merged.insert(format!("PLANE_AGENT_TOKEN_{key}"), pat.clone());
        }
        merged.insert(format!("MM_AGENT_USERID_{key}"), a.mm_user_id.clone());
        merged.insert(format!("MM_AGENT_PAT_{key}"), a.mm_pat.clone());
    }

    // Per-human rows.
    for h in &record.humans {
        let key = h.username.to_ascii_uppercase().replace('-', "_");
        if let Some(id) = &h.plane_user_id {
            merged.insert(format!("HUMAN_PLANE_USERID_{key}"), id.clone());
        }
        if let Some(id) = &h.mm_user_id {
            merged.insert(format!("HUMAN_MM_USERID_{key}"), id.clone());
        }
        merged.insert(format!("HUMAN_EMAIL_{key}"), h.email.clone());
    }

    let mut body = String::new();
    body.push_str("# Generated by `genasis provision` / `genasis team`. DO NOT COMMIT publicly.\n");
    body.push_str(&format!("# Last update: {}\n\n", Local::now().to_rfc3339()));
    for (k, v) in &merged {
        body.push_str(&format!("{k}={v}\n"));
    }

    atomic_write(&path, &body)?;
    chmod_600(&path);
    Ok(())
}

fn append_provision_log(dir: &Path, record: &ProvisionRecord) -> Result<()> {
    let path = dir.join("provision.log");
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&path)
        .with_context(|| format!("open {}", path.display()))?;
    writeln!(
        file,
        "\n========================================\n{} — provision {} ({}) / {} ({})\n----------------------------------------",
        Local::now().to_rfc3339(),
        record.team_name,
        record.team_slug,
        record.app_name,
        record.app_slug
    )?;
    writeln!(file, "humans: {}", record.humans.len())?;
    for h in &record.humans {
        writeln!(file, "  - {} <{}> username={}", h.name, h.email, h.username)?;
    }
    writeln!(file, "agents: {}", record.agents.len())?;
    for a in &record.agents {
        writeln!(
            file,
            "  - {:<14} {:<30} plane={} mm={}",
            a.role,
            a.email,
            a.plane_user_id.as_deref().unwrap_or("(pending)"),
            a.mm_user_id
        )?;
    }
    writeln!(
        file,
        "plane: workspace={} project={} ({})",
        record.plane.workspace_slug, record.plane.project_identifier, record.plane.project_id
    )?;
    writeln!(
        file,
        "mm:    team={} channel={}",
        record.mattermost.team_name, record.mattermost.scrum_channel_name
    )?;
    Ok(())
}

fn role_env_key(role: &str) -> String {
    role.to_ascii_uppercase().replace('-', "_")
}

fn toml_quote(s: &str) -> String {
    // Minimal-quote — works for any string without inner '"' or
    // control chars, which covers every identifier we emit here.
    // (Names with quotes would be malformed input upstream.)
    format!("\"{}\"", s.replace('"', "\\\""))
}

fn atomic_write(path: &Path, body: &str) -> Result<()> {
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, body).with_context(|| format!("write {}", tmp.display()))?;
    fs::rename(&tmp, path)
        .with_context(|| format!("rename {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

#[cfg(unix)]
fn chmod_600(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    if let Ok(meta) = fs::metadata(path) {
        let mut perms = meta.permissions();
        perms.set_mode(0o600);
        let _ = fs::set_permissions(path, perms);
    }
}
#[cfg(not(unix))]
fn chmod_600(_path: &Path) {}

fn read_env_kv(path: &Path) -> Option<BTreeMap<String, String>> {
    let body = fs::read_to_string(path).ok()?;
    let mut m = BTreeMap::new();
    for line in body.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            m.insert(k.trim().to_string(), v.trim().to_string());
        }
    }
    Some(m)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;
    use tempfile::tempdir;

    // Process-wide env is shared across `cargo test` threads. Tests
    // that mutate `GENASIS_SECRETS_ROOT` race each other otherwise
    // (output_dir_for sees half-modified env). Serialize through a
    // global mutex so each test's set→write→assert→unset block runs
    // atomically.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    fn sample_record() -> ProvisionRecord {
        ProvisionRecord {
            team_name: "Marketing Squad".into(),
            team_slug: "ms".into(),
            app_name: "Quiz Demo".into(),
            app_slug: "qd".into(),
            plane: PlaneRecord {
                url: "https://plane.example.com".into(),
                workspace_slug: "agentic".into(),
                project_id: "01HABC".into(),
                project_identifier: "QD".into(),
                project_name: "Quiz Demo".into(),
            },
            mattermost: MattermostRecord {
                url: "https://mm.example.com".into(),
                team_id: "tm123".into(),
                team_name: "team-ms".into(),
                scrum_channel_id: "ch123".into(),
                scrum_channel_name: "scrum-qd".into(),
            },
            humans: vec![HumanRecord {
                name: "Bravo Kim".into(),
                email: "gnoopy@gmail.com".into(),
                username: "gnoopy".into(),
                plane_user_id: Some("plane-user-1".into()),
                mm_user_id: Some("mm-user-1".into()),
            }],
            agents: vec![AgentRecord {
                role: "code-reviewer".into(),
                email: "code-reviewer@realstory.blog".into(),
                plane_user_id: Some("plane-cr".into()),
                plane_pat: None,
                mm_user_id: "mm-cr".into(),
                mm_pat: "mm_pat_xyz".into(),
            }],
        }
    }

    #[test]
    fn write_all_creates_three_files() {
        let dir = tempdir().unwrap();
        let record = sample_record();
        // Unset GENASIS_SECRETS_ROOT to force fallback path.
        let _g = ENV_LOCK.lock().unwrap();
        std::env::remove_var("GENASIS_SECRETS_ROOT");
        let out = write_all(&record, dir.path()).unwrap();
        assert_eq!(out, dir.path());
        assert!(out.join(".env.local").exists());
        assert!(out.join("genasis.toml.snapshot").exists());
        assert!(out.join("provision.log").exists());
    }

    #[test]
    fn env_local_uses_role_keys_with_underscores() {
        let dir = tempdir().unwrap();
        let _g = ENV_LOCK.lock().unwrap();
        std::env::remove_var("GENASIS_SECRETS_ROOT");
        write_all(&sample_record(), dir.path()).unwrap();
        let body = fs::read_to_string(dir.path().join(".env.local")).unwrap();
        // "code-reviewer" → CODE_REVIEWER
        assert!(body.contains("MM_AGENT_PAT_CODE_REVIEWER=mm_pat_xyz"));
        assert!(body.contains("PLANE_AGENT_USERID_CODE_REVIEWER=plane-cr"));
        assert!(!body.contains("CODE-REVIEWER"));
    }

    #[test]
    fn env_local_re_run_merges_existing_keys() {
        let dir = tempdir().unwrap();
        let _g = ENV_LOCK.lock().unwrap();
        std::env::remove_var("GENASIS_SECRETS_ROOT");
        // Pre-write a stray key that the writer must preserve.
        fs::write(dir.path().join(".env.local"), "FOO=bar\n").unwrap();
        write_all(&sample_record(), dir.path()).unwrap();
        let body = fs::read_to_string(dir.path().join(".env.local")).unwrap();
        assert!(body.contains("FOO=bar"));
        assert!(body.contains("GENASIS_TEAM_SLUG=ms"));
    }

    #[test]
    fn secrets_root_redirects_output() {
        let _g = ENV_LOCK.lock().unwrap();
        let root = tempdir().unwrap();
        std::env::set_var("GENASIS_SECRETS_ROOT", root.path());
        let fallback = tempdir().unwrap();
        let out = write_all(&sample_record(), fallback.path()).unwrap();
        std::env::remove_var("GENASIS_SECRETS_ROOT");
        assert_eq!(out, root.path().join("teams").join("ms"));
        assert!(out.join(".env.local").exists());
    }

    #[test]
    fn toml_snapshot_contains_top_level_sections() {
        let dir = tempdir().unwrap();
        let _g = ENV_LOCK.lock().unwrap();
        std::env::remove_var("GENASIS_SECRETS_ROOT");
        write_all(&sample_record(), dir.path()).unwrap();
        let body = fs::read_to_string(dir.path().join("genasis.toml.snapshot")).unwrap();
        assert!(body.contains("[provision]"));
        assert!(body.contains("[plane]"));
        assert!(body.contains("[mattermost]"));
        assert!(body.contains("[[humans]]"));
        assert!(body.contains("[[agents]]"));
        assert!(body.contains("team_slug = \"ms\""));
    }

    #[test]
    fn provision_log_appends() {
        let dir = tempdir().unwrap();
        let _g = ENV_LOCK.lock().unwrap();
        std::env::remove_var("GENASIS_SECRETS_ROOT");
        write_all(&sample_record(), dir.path()).unwrap();
        write_all(&sample_record(), dir.path()).unwrap();
        let body = fs::read_to_string(dir.path().join("provision.log")).unwrap();
        let runs = body.matches("provision Marketing Squad").count();
        assert_eq!(runs, 2);
    }
}
