#!/usr/bin/env bash
# Genasis i18n drift check.
#
# Compares English source documents to their Korean (and other locale)
# mirrors. Three modes:
#
#   --warn          (default)   — emit ::warning:: lines, exit 0.
#   --strict        — emit ::error:: lines, exit 1 if any drift.
#   --list          — print a plain table of drift pairs (used by
#                     `genasis doctor`).
#   --check-mirror-not-empty — verify every English source has a
#                              non-empty mirror; exit 1 if missing.
#   --gen-todo      — emit a GitHub-Issue-body checklist of files that
#                     need translation (used by release-prep.yml to
#                     auto-open the translation-completion PR).
#
# Pairs handled:
#   README.md          ↔ README.ko.md
#   blueprint.md       ↔ blueprint.ko.md
#   progress.md        ↔ progress.ko.md
#   docs/*.md          ↔ docs/ko/*.md      (recursive)
#   docs/ADR/*.md      ↔ docs/ko/ADR/*.md
#
# Drift = English mtime > Korean mtime.

set -euo pipefail

mode="${1:---warn}"

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

# Build the list of (en, ko) pairs.
pairs=()
for f in README.md blueprint.md progress.md; do
    [ -f "$f" ] && pairs+=("$f|${f%.md}.ko.md")
done
while IFS= read -r en_path; do
    rel="${en_path#./docs/}"
    case "$rel" in
        ko/*) continue ;;
        en/*) continue ;;          # Pages locale landing page — has ko/ sibling
        _*) continue ;;            # Jekyll plugins / includes
        example-*) continue ;;     # design-system sample reference, not Genasis own
        famous-agents.md) continue ;;  # Editorial analysis of external agent
                                        # frameworks (Ralph, ECC, etc.); not a
                                        # Genasis product doc — bilingual mirror
                                        # not required.
        i18n/*) ko_path="docs/ko/$rel" ;;
        ADR/*) ko_path="docs/ko/$rel" ;;
        *) ko_path="docs/ko/$rel" ;;
    esac
    pairs+=("$en_path|$ko_path")
done < <(find ./docs -maxdepth 4 -type f -name "*.md" -not -path "./docs/ko/*")

drift_count=0
missing_count=0
table=""

for pair in "${pairs[@]}"; do
    en="${pair%|*}"
    ko="${pair#*|}"

    if [ ! -f "$en" ]; then
        continue
    fi

    if [ ! -f "$ko" ] || [ ! -s "$ko" ]; then
        missing_count=$((missing_count + 1))
        table+="MISSING\\t$en\\t→\\t$ko\\n"
        continue
    fi

    en_mtime=$(stat -c %Y "$en" 2>/dev/null || stat -f %m "$en")
    ko_mtime=$(stat -c %Y "$ko" 2>/dev/null || stat -f %m "$ko")
    if [ "$en_mtime" -gt "$ko_mtime" ]; then
        drift_count=$((drift_count + 1))
        table+="DRIFT\\t$en (en=$en_mtime)\\tnewer than\\t$ko (ko=$ko_mtime)\\n"
    fi
done

case "$mode" in
    --warn)
        if [ "$missing_count" -gt 0 ] || [ "$drift_count" -gt 0 ]; then
            printf "::warning::i18n drift detected: %d missing mirror(s), %d stale mirror(s)\n" \
                "$missing_count" "$drift_count" >&2
            printf "$table" | column -t -s $'\t' -o '  ' >&2 || printf "$table" >&2
        fi
        exit 0
        ;;
    --strict)
        if [ "$missing_count" -gt 0 ] || [ "$drift_count" -gt 0 ]; then
            printf "::error::i18n drift detected: %d missing mirror(s), %d stale mirror(s)\n" \
                "$missing_count" "$drift_count" >&2
            printf "$table" | column -t -s $'\t' -o '  ' >&2 || printf "$table" >&2
            exit 1
        fi
        exit 0
        ;;
    --list)
        if [ "$missing_count" -eq 0 ] && [ "$drift_count" -eq 0 ]; then
            echo "No drift detected."
        else
            printf "$table" | column -t -s $'\t' -o '  '
        fi
        exit 0
        ;;
    --check-mirror-not-empty)
        if [ "$missing_count" -gt 0 ]; then
            printf "::error::%d missing mirror file(s)\n" "$missing_count" >&2
            printf "$table" >&2
            exit 1
        fi
        exit 0
        ;;
    --gen-todo)
        if [ "$missing_count" -eq 0 ] && [ "$drift_count" -eq 0 ]; then
            echo "No translation work needed."
            exit 0
        fi
        cat <<'BODY'
## Translation completion checklist

The following Korean mirrors are stale or missing relative to the
English source. Update them before tagging the next release.

| Status | English source | Korean mirror |
|---|---|---|
BODY
        printf "$table" | while IFS=$'\t' read -r status en arrow ko; do
            printf "| %s | \`%s\` | \`%s\` |\n" "$status" "$en" "$ko"
        done
        echo
        echo "Generated by \`scripts/check-i18n-drift.sh --gen-todo\`."
        exit 0
        ;;
    *)
        echo "usage: $0 [--warn|--strict|--list|--check-mirror-not-empty|--gen-todo]" >&2
        exit 2
        ;;
esac
